create-config: ensure error msg is printed to stderr

diff --git a/bin/create-config b/bin/create-config
--- a/bin/create-config
+++ b/bin/create-config
@@ -11,7 +11,7 @@ print_help() {
 }
 error() {
   print_help
-  echo "$*"
+  echo "ERROR: $*" >&2
   exit 1
 }
 
